---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gwpe7134/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp login.html $DEPLOYPATH
    - /bin/cp daftar.html $DEPLOYPATH
    - /bin/cp dashboard.html $DEPLOYPATH
    - /bin/cp tools.html $DEPLOYPATH
    - /bin/cp admin.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp data-search.html $DEPLOYPATH
    - /bin/cp username-intel.html $DEPLOYPATH
    - /bin/cp domain-lookup.html $DEPLOYPATH
    - /bin/cp email-check.html $DEPLOYPATH
    - /bin/cp phone-check.html $DEPLOYPATH
    - /bin/cp report.html $DEPLOYPATH
